version: '3.4'

services: 
  go-backend:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
    env_file:
      - ./go-backend/.env
    ports:
      - "3001:3000"
    volumes:
      - ./go-backend:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file: 
      - ./backend/.env
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - '4200:80'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on: 
      - backend